apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volume
  annotations:
    pv.beta.kubernetes.io/gid: "4096"
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: volume1
    readOnly: false
  persistentVolumeReclaimPolicy: Retain