apiVersion: v1
kind: Pod
metadata:
  name: glusterfs-nginx
  labels:
    name: glusterfs-nginx
spec:
  containers:
  - name: glusterfs-nginx
    image: nginx:latest
    ports:
    - name: web
      containerPort: 80
    volumeMounts:
    - name: gluster-vol1
      mountPath: /usr/share/nginx/html
      readOnly: false
  volumes:
  - name: gluster-vol1    
    persistentVolumeClaim:
      claimName: gluster-claim
